# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
    - linux
    - osx
julia:
    - 1.0
    - nightly
branches:
    only:
        - master
after_success:
    - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Coveralls.submit(process_folder())'
    - julia -e 'using Pkg; Pkg.dir("Currencies")); Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
    - julia -e 'using Pkg; Pkg.add("Documenter")'
    - julia -e 'using Pkg; include(joinpath("docs", "make.jl"))'
git:
    depth: 99999
